Fix `--manifest-path` argument usage for Android build
Whereas `cargo` expects the `--manifest-path` argument after the `build` command, `cargo ndk` only supports arguments being specified before the `build` command, which was causing the Android build to fail with:

```
error: Failed loading manifest
error: No such file or directory (os error 2)
```

Regression from #8557.